before_install:
  - sudo systemsetup -settimezone Europe/Berlin
language: swift
osx_image: xcode11
xcode_workspace: Books.xcworkspace
xcode_scheme: Books
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone Xs
