osx_image: xcode12.2
language: swift
xcode_workspace: Books.xcworkspace
xcode_scheme: Books
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 12 Pro
before_install:
  - sudo systemsetup -settimezone Europe/Berlin
  - defaults write com.apple.iphonesimulator CaptureKeyboardInput 1
  - defaults write com.apple.iphonesimulator ConnectHardwareKeyboard 0
  - for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
script:
  - set -o pipefail && xcodebuild build-for-testing -workspace Books.xcworkspace -scheme Books -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 12 Pro' -derivedDataPath DerivedData -parallel-testing-enabled NO
  - xcodebuild test-without-building -workspace Books.xcworkspace -scheme Books -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 12 Pro' -derivedDataPath DerivedData -parallel-testing-enabled NO


